### ISSUE TITLE
mapping script clean-up

### ISSUE THREAD

**Issue by teixeirak** [forc-db/IPCC-EFDB-integration#10]
@ValentineHerr , here's a running list of small things to fix:
- [x] plot ID listed as 'NA' (Meakem)
- [x] authors are messed up in the citation: "Meakem, V., Tepley, A. J., Gonzalez-Akre, E. B., Herrmann, V., Muller-Landau, H. C., Wright, S. J., √¢‚Ç¨¬¶ Anderson-Teixeira, K. J". Ive noticed that this is common in many-author citations.
- [x] [change vegetation type description](https://github.com/forc-db/IPCC-EFDB-integration/issues/9)
- [x] for stand.age=999, list as mature
- [x] reorder/ re-categorize some variables (see two commits ForC-EFDB_mapping between ~5 and 5:30pm on 3/31)
- [x] "disturbance" seems to be dropped/ messed up. For BCI, for example, we just get "disturbance year: 1500." What we want in this instance is "No disturbance since 1500."
- [x] currently we have, e.g., "biogeographic zone: North America". Let's be consistent with biogeographic zone vs continent. For this example (Panama), we'd want either "continent: North America" or "biogeographic zone: neotropics". I think continent would be better in this case, but I'm not sure where you're getting that or how the system would classify islands/ countries that span continents or include continent + island. If it's a good system, stick with that. Otherwise, let's send the biogeographic zones that we have in the sites table.  
- [x] limit dates to one point after the decimal (avoid, e.g., "Date of Measurement: 2002.413699-2001.49589")
- [x] latest Meakem file is empty!
- [x] delete soil notes
- [x] limit dates for history events one point after the decimal (avoid, e.g., "disturbance year: 1976.915301")
- [x] for the Ngo study, there's a comment "95%CI is NA because only 1 plot was measured" for total.ecosystem_C but not the other variables with missing CIs.  n>1 in the measurements file, but CIs not reported...
- [x] limit n decimal places on calculated 95% SIs
- [x] fix whatever bug is causing missing 95%CI cells: [ Uhl. Could the cell with absent confidence limits be populated as NA or unknown?  |      Gonzalez-Akre. Could the cell with absent confidence limits be populated as NA or unknown, or can it be calculated?  |      Lutz. The value in column D does not have CI? Maybe, some technical error occurred?]
- [x] add "biomass allometry source" (allometry.citation) for variables for which `requires.allometry` =1. 
- [x] fix missing measurement dates for biomass increments/ fluxes? (see Meakem, Chave)

**Comment by ValentineHerr** [comment]
hmmm issue with citation is annoying... I think it is because the function that pulled those stops pulling names after x number of names, and filles the rest with "..." which is apparently a special character.

@teixeirak, should we have Teagan fill those with all co-authors or do you think it is best to keep those "..." (so that citations are not too long). In the later case it should be easy for me to replace the special character with actual 3 dots.

**Comment by ValentineHerr** [comment]
plot.ID should be fixed now

**Comment by teixeirak** [comment]
> hmmm issue with citation is annoying... I think it is because the function that pulled those stops pulling names after x number of names, and filles the rest with "..." which is apparently a special character.
> 
> @teixeirak, should we have Teagan fill those with all co-authors or do you think it is best to keep those "..." (so that citations are not too long). In the later case it should be easy for me to replace the special character with actual 3 dots.

3 dots is fine.

**Comment by teixeirak** [comment]
@ValentineHerr , note that I've added a few items to the list at the top of this issue.

**Comment by ValentineHerr** [comment]
> [ ] reorder/ re-categorize some variables (see two commits ForC-EFDB_mapping between ~5 and 5:30pm on 3/31)

This should be automatic when ForC-EFDB_mapping is edited accordingly. Let me know if you see that it is not.

**Comment by ValentineHerr** [comment]
> * currently we have, e.g., "biogeographic zone: North America". Let's be consistent with biogeographic zone vs continent. For this example (Panama), we'd want either "continent: North America" or "biogeographic zone: neotropics". I think continent would be better in this case, but I'm not sure where you're getting that or how the system would classify islands/ countries that span continents or include continent + island. If it's a good system, stick with that. Otherwise, let's send the biogeographic zones that we have in the sites table.

Currently `biogeog` in SITES is the continent.... I agree that we should have actual biogeographic zones.... do we have that map? I need to check an and add that to the SCRIPT that fills this type of info for SITES... but for now, I'll call it Continent. I'll create an issue in ForC about this.

**Comment by teixeirak** [comment]
@ValentineHerr , note new item above

**Comment by teixeirak** [comment]
@ValentineHerr , two more minor fixes above. I just realized that I think we'd regret not including info about the allometries applied, when available.

**Comment by ValentineHerr** [comment]
@teixeirak, for allometries, 2 questions:
- what to do when both allometry_1and allometry_2 are filled? concatenate both?
- should I bring in the full citation reference and not just allometry.citation key?

**Comment by teixeirak** [comment]
Yes, I guess we should concatenate both, assuming they're different (sometimes same reference has more than one code). Yes, pleaase bring in full citation.

**Comment by ValentineHerr** [comment]
The following citation.ID in ALLOMETRY need full reference in CITATIONS

- [ ] Brown_1989_bemf
- [ ] Brown_1997_ebab
- [ ] Weaver_1992_tbef
- [ ] Ovington_1970_bacc
- [ ] Crow_1980_arca
- [ ] Niiyama_2010_eorb
- [ ] Kenzo_2009_doar
- [ ] Ker_1980_tbef
- [ ] Ker_1984_befs

**Comment by teixeirak** [comment]
@ValentineHerr , are these completely missing from citations? Or just need a DOI?

**Comment by ValentineHerr** [comment]
need DOI and/or citation.citation and/or citation.language

**Comment by teixeirak** [comment]
Do you need any of those for this first batch?

**Comment by ValentineHerr** [comment]
Yes, need **Niiyama_2010_eorb** for Ngo_2013_csip


and FYI, here are all the references we need them for:

- [ ]  Lugo_1992_cott
- [ ]  Crow_1980_arca
- [ ]  Aide_1995_fria
- [ ]  Letcher_2009_rrob
- [ ]  Delaney_1997_tdoo
- [ ]  Ngo_2013_csip
- [ ]  Fleming_1998_conm

**Comment by teixeirak** [comment]
Hmmm... we don'nt seem to have Niiyama in here at all. I'll track it down.

**Comment by teixeirak** [comment]
> The following citation.ID in ALLOMETRY need full reference in CITATIONS

I've asked @Troger4 to prioritize these (https://github.com/forc-db/ForC/issues/223).

**Comment by teixeirak** [comment]
@ValentineHerr , note addition above.

**Comment by ValentineHerr** [comment]
the date issue is because we some  "flux" were changed to "increment" and my script was not up to date with that.
