### ISSUE TITLE
include original units

### ISSUE THREAD

**Issue by teixeirak** [forc-db/IPCC-EFDB-integration#13]
@ValentineHerr , I've added fields for original units to ForC. Could you please program these in?

**Comment by ValentineHerr** [comment]
@teixeirak, I don't need to worry about `C.conversion.factor`, right? This is filled with the conversion factor used in the original paper?

I only need to fill EFDB's `Value in Common Units` and `Common Unit` if ForC's `mean.in.original.units` is entered and non NA, right?

**Comment by teixeirak** [comment]
> I don't need to worry about `C.conversion.factor`, right? This is filled with the conversion factor used in the original paper?

Correct. There's no direct need for that from IPCC, but I decided it would be good practice to record.

**Comment by teixeirak** [comment]
> I only need to fill EFDB's `Value in Common Units` and `Common Unit` if ForC's `mean.in.original.units` is entered and non NA, right?

Correct, BUT we should throw a warning (that record hasn't been adequately completed) if `mean.in.original.units` is NAC, as we need to check this for IPCC.

**Comment by ValentineHerr** [comment]
ok, I'll add a warning in `Comments from Data Provider`.

For `Common Unit`, I assume we need to enter some "standardized" units that are listed in the EFDB form.
I think the easiest way would be to have a document that maps ForC's `original.units` to that. Is that okay with you? I think there is no cases involved right now, but I may still fill the the first row with the one value we currently have (Mg C ha-1).
And I'll code something to remind us to fill in that file when we have new values in `original.units`.

**Comment by teixeirak** [comment]
The common units are what's in ForC: Mg C ha-1 , Mg dry matter -1, etc.

**Comment by ValentineHerr** [comment]
Oh, I can write those in directly, okay.

**Comment by ValentineHerr** [comment]
Ok I have it to say: `original units note: it is possible the record is not in the original publication's unit.`  if `mean.in.original.units` is "NAC", in `Comments from Data Provider` ( after confidence notes and before biomass allometry source).

Is that okay?

**Comment by teixeirak** [comment]
Oh, I actually meant that it would generate a warning to us (perhaps included as part of issue #16 ). But I think it's good to leave that in the code in case one sneaks past us, though.

**Comment by ValentineHerr** [comment]
ha okay, I hadn't carefully looked at that other issue.
It will be easy to remove. We will just need to delete the line I am adding in the mapping document.

**Comment by teixeirak** [comment]
I think we can close this.
