### ISSUE TITLE
Come up with system for indicating which studies are ready to process

### ISSUE THREAD

**Issue by teixeirak** [forc-db/IPCC-EFDB-integration#18]
@ValentineHerr (and @mawilliams99 ), we need a good system to communicate which studies we want to send into the pipeline for sending to EFDB (i.e., generate [files to review](https://github.com/forc-db/IPCC-EFDB-integration/tree/main/data/1-to-review)). This is step 7 [here](https://github.com/forc-db/IPCC-EFDB-integration/blob/main/doc/ForC-EFDB_mapping/Data%20review%20process.md)). 

For the first round, I sent Valentine a list (see issue #1), and some of those (not necessarily high priority) remain in [files to review](https://github.com/forc-db/IPCC-EFDB-integration/tree/main/data/1-to-review). (@ValentineHerr , I think we should just delete these. They still need various levels of review, and aren't necessarily high priority.)

@ValentineHerr , from a quick look, I didn't see in your code where you entered the studies identified. What would be a convenient way to communicate these?  Perhaps add a column in citations.csv indicating EFDB status (ready to run & send, sent...)? Or have such a file here?

**Comment by teixeirak** [comment]
note: I think it's more productive to do most of the review in the original ForC format, and only send to `[1-to-review](https://github.com/forc-db/IPCC-EFDB-integration/tree/main/data/1-to-review)` once we're confident that it's good. Perhaps a good workflow to start would be for Madison to check data in ForC against the original pub, and then I review/approve the files in `[1-to-review](https://github.com/forc-db/IPCC-EFDB-integration/tree/main/data/1-to-review)`.

**Comment by teixeirak** [comment]
For now, I'll start a list here of studies that are ready:

- [ ] McGarvey_2015_csio

**Comment by ValentineHerr** [comment]
> @ValentineHerr , from a quick look, I didn't see in your code where you entered the studies identified. What would be a convenient way to communicate these? Perhaps add a column in citations.csv indicating EFDB status (ready to run & send, sent...)? Or have such a file here?

I had hard-coded the list of citations that you had listed [here](https://github.com/forc-db/IPCC-EFDB-integration/blob/88bb846bc7a49b4b86ee1dc505e33ff0fcf3f28d/scripts/1_ForC_to_IPCC_formatting.R#L588-L604).

I think that either a new column in the CITATIONS table or a new .csv file (only one column for citation.ID suffices) in this repo would be fine. I don't think we need to keep track of status as [this folder](https://github.com/forc-db/IPCC-EFDB-integration/tree/main/data/4-transferred-to-EFDB) should list all what has been transferred.

Also, it does not matter if a citation that has already been transferred stays in the list as the system makes it that if there is no new data entered (or approved, e.g. if it was listed as suspicious and is not anymore) from that citation, nothing will be generated.

**Comment by ValentineHerr** [comment]
> note: I think it's more productive to do most of the review in the original ForC format, and only send to _[1-to-review](https://github.com/forc-db/IPCC-EFDB-integration/tree/main/data/1-to-review)_ once we're confident that it's good. Perhaps a good workflow to start would be for Madison to check data in ForC against the original pub, and then I review/approve the files in _[1-to-review](https://github.com/forc-db/IPCC-EFDB-integration/tree/main/data/1-to-review)_.

That is fine with me.

**Comment by teixeirak** [comment]
I added `EFDB.ready` field to the citations table metadata. @mawilliams99 , could you please add this to ForC_citations when you have a chance? Then, you can populate with "0" for all studies but those in [this folder](https://github.com/forc-db/IPCC-EFDB-integration/tree/main/data/4-transferred-to-EFDB), which get "1". McGarvey_2015_csio should also get "1", as should any the studies you finish reviewing.

Then, @ValentineHerr , you can have your script reference this field.

**Comment by ValentineHerr** [comment]
Hopefully I did not create a conflict by doing this (I reffered to the wrong issue but the commit is [here](https://github.com/forc-db/ForC/commit/4feab8ee9f572bff415ea44c090eef35d3c183b5)). 
If i did, @mawilliams99, you can revert my  commit

**Comment by teixeirak** [comment]
I think we likely have a conflict with @mawilliams99's version (at least the measurements file) after you updated everything, @ValentineHerr , and after I fixed the one error. Sorry, @mawilliams99! The easiest fix is probably to save your copy under a temporary name, pull the new version, and copy your changes in there. Alternatively, sometimes GitHub may be able to merge conflicting copies when the changes themselves don't conflict (have seen it work for .Rmd files, but not sure about .csv).

**Comment by ValentineHerr** [comment]
I added source.type (but didn't fill) in CITATIONS so you don't need to do it @mawilliams99, unless you have a conflict and need to revert my commit.

If you are having issues with merging your changes in MEASUREMENTS, let me know and I can help you navigate that.

**Comment by ValentineHerr** [comment]
FYI, @teixeirak McGarvey_2015_csio is ready to review [here](https://github.com/forc-db/IPCC-EFDB-integration/tree/main/data/1-to-review)

**Comment by teixeirak** [comment]
I just approved McGarvey_2015_csio.  I believe we can close this issue.
