### ISSUE TITLE
Add data source type

### ISSUE THREAD

**Issue by teixeirak** [forc-db/IPCC-EFDB-integration#22]
This is for the `Source of Data` field. In the vast majority of cases, it will be Peer-reviewed journal , but there are some theses and book chapters.

**Comment by teixeirak** [comment]
@mawilliams99 , could you please add this field to ForC_citations?

@ValentineHerr , we'll want to change the coding from assuming "peer-reviewed journal" to drawing from this field.

**Comment by ValentineHerr** [comment]
I did this [here](https://github.com/forc-db/IPCC-EFDB-integration/blob/5b214987f3761a1287e4eda36d839128925f06cf/scripts/1_ForC_to_IPCC_formatting.R#L555)
