### ISSUE TITLE
studies to review

### ISSUE THREAD

**Issue by teixeirak** [forc-db/IPCC-EFDB-integration#23]
@mawilliams99 , here's a running list of studies to review. Please check them off when done.

## studies that look straightforward:

- [x] Ishihara_2016_anmf – looks like appendix S3 has the data
- [x] Manlay_2002_cnap - **This one needs to be revisited. See [this issue](https://github.com/forc-db/ForC/issues/247).**
- [x]  Ma_2012_rdri
- [x] Sharma_2010_tdac
- [x] Swamy_2004_tgba
- [x] Neeff_2005_agmf (likely digitized)
- [x] van Breugel_2013_soes (likely digitized)
- [x] Broadbent_2014_isas
- [x] Wirth_2002_fast - sent (7 records)
- [x] Wirth_1999_abas - reviewed by KAT
- [x] Wirth_2002_babc - reviewed by KAT
- [x] Litton_2004_eotd (there are some duplicates, but just in measurements)- reviewed by KAT
- [x] Litton_2003_scde (there are some duplicates, but just in measurements) - reviewed by KAT
- [ ] Uri_2012_bpac
- [x] Litton_2003_baab - reviewed by KAT
- [ ] Ryan_1996_ffwa
- [ ] Bond-Lamberty_2004_corr are duplicates and can be deleted

## studies with digitized data (just need to mark that and move on)
- [x] Powers_2012_csaa
- [x] Dupuy_2012_paco

## studies with duplicates:

*These are more complicated, so we will return to them later. Please disregard for now.*
- [ ] Poorter_2016_bron
- [ ] Lewis_2009_icsi 
- [ ] Krankina_1999_nbfs
- [x] Crowell_1994_vdia

**Comment by teixeirak** [comment]
@mawilliams99 , a reminder to please help keep this up to date. More importantly, could you please double check that the studies you've reviewed are flagged as ready to run in the citations file?

I'm concerned that we could be reviewing some studies, and potentially forgetting to flag as ready to run in the citations file, and hence losing the record of what we've reviewed.  This is easy to forget and not a great system... perhaps we could think of something better?

**Comment by mawilliams99** [comment]
@teixeirak Just wanted to flag this so you can see the most recent updates

**Comment by mawilliams99** [comment]
I'm working on Uri_2012_bpac currently @teixeirak

**Comment by teixeirak** [comment]
Thanks!

It does appear that there are some duplicates loaded from Cook-Patton_2020_mcap (Uri_2012_bpac record numbers between 33604-33626).  Please figure out which are true duplicates, and I can help with removing/ resolving (requires a bit of recordkeeping elsewhere).
