### ISSUE TITLE
figure out what's happening with past last use & land classification

### ISSUE THREAD

**Issue by teixeirak** [forc-db/IPCC-EFDB-integration#29]
@ValentineHerr , I'm not sure if we're consistently getting the past land use & land classification right. This is based on [these instructions](https://github.com/forc-db/IPCC-EFDB-integration/blob/main/doc/ForC-EFDB_mapping/defining_land_subcategory.md).

Here's an example (Feldpausch_2004_cana) where the disturbance history for all was the following sequence: 
<img width="945" alt="image" src="https://user-images.githubusercontent.com/6355854/136269064-13a0817d-0fa9-4fe3-821d-2ac14c1ed177.png">

All have `distmrs.type` = grazed in plots.

So, they should all be classified as pasture converted to forest (5-FL-2 and 3.B.1.b.ii), yet 3 get classified as forest remaining forest (F-FL-2 and 3.B.1.a):
<img width="1130" alt="image" src="https://user-images.githubusercontent.com/6355854/136268412-cad6c2e9-cb28-4b9d-9f6e-6f38ddb415ed.png">

This

**Comment by teixeirak** [comment]
This also relates to issue #7, and I'll post something there.

**Comment by teixeirak** [comment]
These two examples are technically wrong-- higher priority to solve this issue.

**Comment by ValentineHerr** [comment]
For past LU, I also have cases that don't map...

![image](https://user-images.githubusercontent.com/19673377/136285106-ecb0d6b3-4431-4e3b-bd90-f68fa3dad1bf.png)
Two last columns are min stand age and max stand age, for all sites for which it didn't map.

I'll have to return to this tomorrow

For info, here is the code.
```
### Define past_LU
ForC_simplified$past_LU <- ""

#### stand.age ≥ 20 or missing value for stand.ag --> past_LU = current_LU

ForC_simplified$past_LU[my_is.na(ForC_simplified$stand.age) | ForC_simplified$stand.age >=20] <- ForC_simplified$current_LU[my_is.na(ForC_simplified$stand.age) | ForC_simplified$stand.age >=20] 


#### stand.age < 20 --> PAST LAND-USE is dependent on distmrs.type
unique(ForC_simplified$distmrs.type)

ForC_simplified$past_LU[(!my_is.na(ForC_simplified$stand.age) & ForC_simplified$stand.age <20) & ForC_simplified$distmrs.type %in% "Grazed"] <- "Grassland"
ForC_simplified$past_LU[(!my_is.na(ForC_simplified$stand.age) & ForC_simplified$stand.age <20) & ForC_simplified$distmrs.type %in% c("Cultivation", "Shifting cultivation", "Tillage")] <- "Cropland"
ForC_simplified$past_LU[(!my_is.na(ForC_simplified$stand.age) & ForC_simplified$stand.age <20) & ForC_simplified$distmrs.type %in% c("Agriculture_generic")] <- "Cropland or Grassland"
ForC_simplified$past_LU[(!my_is.na(ForC_simplified$stand.age) & ForC_simplified$stand.age <20) & ForC_simplified$distmrs.type %in% c("No disturbance", "No severe disturbance", "Flood", "Forest dieback", "Landslide","Major Storm")] <- ForC_simplified$current_LU[(!my_is.na(ForC_simplified$stand.age) & ForC_simplified$stand.age <20) & ForC_simplified$distmrs.type %in% c("No disturbance", "No severe disturbance", "Flood", "Forest dieback", "Landslide","Major Storm")]
ForC_simplified$past_LU[(!my_is.na(ForC_simplified$stand.age) & ForC_simplified$stand.age <20) & ForC_simplified$distmrs.type %in% c("Cut", "Harvest")] <- ForC_simplified$current_LU[(!my_is.na(ForC_simplified$stand.age) & ForC_simplified$stand.age <20) & ForC_simplified$distmrs.type %in% c("Cut", "Harvest")]

ForC_simplified$past_LU[(!my_is.na(ForC_simplified$stand.age) & ForC_simplified$stand.age <20) & ForC_simplified$distmrs.type %in% c("Burned", "StandClearing") | my_is.na( ForC_simplified$distmrs.type)] <- ""

unique(ForC_simplified$past_LU)
sum(ForC_simplified$past_LU[(!my_is.na(ForC_simplified$stand.age) & ForC_simplified$stand.age <20)]%in%"")
unique(ForC_simplified[ForC_simplified$past_LU %in% "", c("distmrs.type", "stand.age", "past_LU")]) # should be empty
```

**Comment by ValentineHerr** [comment]
I think this should be fixed but I'll let you double check and close @teixeirak

**Comment by ValentineHerr** [comment]
I also see that we "canceled" a Manlay that had 17 data points with NA. WE eventually sent 28 data points with no NA
