### ISSUE TITLE
why are we missing records from Litton_2004_eotd?

### ISSUE THREAD

**Issue by teixeirak** [forc-db/IPCC-EFDB-integration#30]
@ValentineHerr (or maybe @mawilliams99 ), I'm trying to figure out why a bunch of variables from Litton_2004_eotd are not getting transferred...

We expect all these 10 variables, each from 4 sites, so 40 records:
<img width="179" alt="image" src="https://user-images.githubusercontent.com/6355854/140808398-6d4a920b-6054-45cc-9c71-720c9140b21f.png">

But we only get these 6 variables, each from 4 sites, so 24 records:
<img width="403" alt="image" src="https://user-images.githubusercontent.com/6355854/140808025-bc127d1d-aef8-489d-b5a4-0ae2f3f651e1.png">

Missing variables:
- deadwood
- delta.agb
- delta.O.horizon
- soil_C

**Comment by teixeirak** [comment]
The missing records are in ForC_simplified (at least some), and the variables marked off in ForC_variables_mapping as variables to send to EFDB. They're all marked as coming from a table... 

Any idea what's going on?

We shouldn't send this study until this is resolved, so I'll reject it.

**Comment by ValentineHerr** [comment]
Looking into this now

**Comment by ValentineHerr** [comment]
Ok... it is because we asked to ignored calculated values, including if there was a "+" or a "-".... but "-" is used a lot as a dashed.... I am removing it...

**Comment by ValentineHerr** [comment]
I think we can close this
