### ISSUE TITLE
move elevation and Koeppen to "Other Properties"

### ISSUE THREAD

**Issue by teixeirak** [forc-db/IPCC-EFDB-integration#31]
From Valentyna: 

It would be great if the info on elevation and Koeppen climate zone, where it exists, is moved to the "Other properties" cell.

**Comment by teixeirak** [comment]
Also, please  map `data.location.within.source` to "Comments from Data Provider".

**Comment by ValentineHerr** [comment]
those 2 changes should be implemented in the next run.

**Comment by teixeirak** [comment]
Thanks!
