### ISSUE TITLE
check data issues identified Jan 2022

### ISSUE THREAD

**Issue by teixeirak** [forc-db/IPCC-EFDB-integration#32]
@mawilliams99 , let's prioritize dealing with the data issues that Valentyna identified.

I've created [this file](https://github.com/forc-db/IPCC-EFDB-integration/blob/main/doc/data_review/2022_01_Data_check.csv) from the one she sent. Let's fill in our responses in the comments field. I will give it a quick review to fill anything that I should fill. 

A couple general comments:
- It's likely that all the 0.0 values are both legitimate and meaningful.
- Referring to the `data location within source` field should solve a lot of these

**Comment by mawilliams99** [comment]
Okay I’ll work on this today. Thank you!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Kristina Anderson-Teixeira ***@***.***>
Sent: Monday, January 24, 2022 8:43:35 AM
To: forc-db/IPCC-EFDB-integration ***@***.***>
Cc: Williams, Madison ***@***.***>; Mention ***@***.***>
Subject: [forc-db/IPCC-EFDB-integration] check data issues identified Jan 2022 (Issue #32)


External Email - Exercise Caution

@mawilliams99<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmawilliams99&data=04%7C01%7CWilliamsM%40si.edu%7C87be9b63bab34183bfb108d9df3f8506%7C989b5e2a14e44efe93b78cdd5fc5d11c%7C0%7C0%7C637786286183115802%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=yd6v0xicYt5Z%2FIGMrhIUi7hv%2BHE57tnQvjm0YvIQucI%3D&reserved=0> , let's prioritize dealing with the data issues that Valentyna identified.

I've created this file<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fforc-db%2FIPCC-EFDB-integration%2Fblob%2Fmain%2Fdoc%2Fdata_review%2F2022_01_Data_check.csv&data=04%7C01%7CWilliamsM%40si.edu%7C87be9b63bab34183bfb108d9df3f8506%7C989b5e2a14e44efe93b78cdd5fc5d11c%7C0%7C0%7C637786286183115802%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Nxosqm0aEjlBUGHmrZ2MeFGJGX6yAJQDyxsURwGcnpk%3D&reserved=0> from the one she sent. Let's fill in our responses in the comments field. I will give it a quick review to fill anything that I should fill.

A couple general comments:

  *   It's likely that all the 0.0 values are both legitimate and meaningful.
  *   Referring to the data location within source field should solve a lot of these

—
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fforc-db%2FIPCC-EFDB-integration%2Fissues%2F32&data=04%7C01%7CWilliamsM%40si.edu%7C87be9b63bab34183bfb108d9df3f8506%7C989b5e2a14e44efe93b78cdd5fc5d11c%7C0%7C0%7C637786286183115802%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=B6u5vnD2i3HHynVI9B2V13NTMwp0okBIrtd%2FciisKsE%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAKITRFN5JMCS4JRPJ62FGQDUXVJQPANCNFSM5MVNHQNQ&data=04%7C01%7CWilliamsM%40si.edu%7C87be9b63bab34183bfb108d9df3f8506%7C989b5e2a14e44efe93b78cdd5fc5d11c%7C0%7C0%7C637786286183115802%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=mqEp83YCaxjGQN276dmMlIO46Tkety%2FqigOaIQoxEFU%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CWilliamsM%40si.edu%7C87be9b63bab34183bfb108d9df3f8506%7C989b5e2a14e44efe93b78cdd5fc5d11c%7C0%7C0%7C637786286183115802%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=hsFSuPuC%2FcNS7icpOHzp8Aual9ddCUODlupJ5xdEDb4%3D&reserved=0> or Android<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7CWilliamsM%40si.edu%7C87be9b63bab34183bfb108d9df3f8506%7C989b5e2a14e44efe93b78cdd5fc5d11c%7C0%7C0%7C637786286183115802%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=IKzqtFQhXtj3kVs7%2F6Ln98PMdSPfJfFXsyh%2BoBPsXiQ%3D&reserved=0>.

**Comment by mawilliams99** [comment]
@ValentineHerr
