### ISSUE TITLE
create map figure for publication

### ISSUE THREAD

**Issue by teixeirak** [forc-db/IPCC-EFDB-integration#33]
@mawilliams99 and/or @ValentineHerr , for our publication, we'll want to include a global map showing locations with relevant data and data sent to EFDB. I think it would be best to have an underlay of the FAO ecozones (plus our normal forest cover map), as IPCC uses those a lot for classification.  

Here's the current placeholder with a caption that tries to describe what I envision. There is, of course, room to adjust this to your vision/ what's practical, so please don't hesitate to suggest improvements. 

<img width="878" alt="image" src="https://user-images.githubusercontent.com/6355854/163028422-91015922-f2f5-4232-83ea-89bdae6690e5.png">

**Comment by teixeirak** [comment]
We'll want all the figures for the paper in [this folder](https://github.com/forc-db/IPCC-EFDB-integration/tree/main/doc/manuscript/figures_tables). If it's easier, we can create in the main GitHub repo and copy them over here.

**Comment by ValentineHerr** [comment]
- [ ] do FAO and drop dominant Tree Type
- [ ] keep only variables relevant to EFDB, add triangles on top with color representing no of records already sent

**Comment by ValentineHerr** [comment]
- [ ] add script creating the map to the CI in ForC, so it gets upadated when there is an update to master ForC (but it won't get updated when they are changes to this repo...)

**Comment by teixeirak** [comment]
![image](https://user-images.githubusercontent.com/6355854/163261456-84c79968-a9c5-4972-aa60-020fd1032a86.png)

@ValentineHerr , this is gorgeous! The one thing I'd change is to emphasize the sites with data sent to EFDB a little more, if possible: make sure they're always on top, maybe make the symbols bigger or give them a bold outline.

@mawilliams99 , any comments?

**Comment by teixeirak** [comment]
@mawilliams99 , one thing it would be helpful for you to do is fill in the FAO ecozone codes in the legend for this figure. They go here (currently line 328):

<img width="1184" alt="image" src="https://user-images.githubusercontent.com/6355854/163387801-a7e82784-e170-4ea5-89ec-ef1f3057ee7c.png">

**Comment by ValentineHerr** [comment]
I made the triangles bigger and their outline in bold. But I feel that putting them in the foreground would cover too many of the circles. What do you think @teixeirak and @mawilliams99 ?

(I also corrected the legend, which was wrong for n records - I need to do that for the other maps too.)

![image](https://user-images.githubusercontent.com/19673377/163416341-3711a2e5-c829-45d2-b707-2dff9fd65bb0.png)

**Comment by teixeirak** [comment]
Thanks! That helps. I personally would put them in the foreground and not worry about covering other sites. The main point illustrated here is that we have a lot of data/ broad coverage, but I think we really want to emphasize what's already in EFDB.

**Comment by teixeirak** [comment]
Looks great! 

All that's left now is to fill in the legend with the codes, so I'll assign this issue to @mawilliams99.
