### ISSUE TITLE
finish histogram for publication

### ISSUE THREAD

**Issue by teixeirak** [forc-db/IPCC-EFDB-integration#34]
@mawilliams99 and @ValentineHerr , 

Madison started [this histogram](https://github.com/forc-db/ForC/blob/master/figures/Williams_Histogram_of_dominant_vegetation.png) (thank you!) for her paper. Let's get this finished.

Here's the placeholder with a caption that tries to describe what I'd envision:
<img width="881" alt="image" src="https://user-images.githubusercontent.com/6355854/163029280-aca6698e-8212-4d05-aced-d01bc1f9c43d.png">

Again, there's plenty of room for creativity/ other suggestions here. 

@mawilliams99 , are you hitting a sticking point on this? 
@ValentineHerr , I believe you still have some time on this project that we could use to get this worked out?

**Comment by teixeirak** [comment]
We'll want all the figures for the paper in [this folder](https://github.com/forc-db/IPCC-EFDB-integration/tree/main/doc/manuscript/figures_tables). If it's easier, we can create in the main GitHub repo and copy them over here.

**Comment by ValentineHerr** [comment]
@mawilliams99 where is your script for this figure?

@teixeirak, what should be on the x-axis?

**Comment by ValentineHerr** [comment]
can you define relevant to EFDB? 
Is it what is EFDB_ready but not sent yet, or just everything that would be sent (according to our criterias) if we assumed everything had been reviewed and flagged as EFDB_ready? (which might be a stretch if, for example, ForC does not specify that the measurement is found in a figure or is calculated, etc...).

**Comment by teixeirak** [comment]
It's the latter, or more simply all of the records for the variables we send.

**Comment by ValentineHerr** [comment]
Does this look good?
![image](https://user-images.githubusercontent.com/19673377/163204431-20329b8f-441e-4afc-b34a-f81eebed5786.png)

**Comment by ValentineHerr** [comment]
"relevant" is n records with variable name to provide to IPCC, that is not "suspected.duplicate" (in ForC_simplified) and for which we have citation and language (was easier to add code for histogram after that filter, I can change if necessary)

**Comment by ValentineHerr** [comment]
Do with FAO instead

**Comment by ValentineHerr** [comment]
- [ ] add one hist for continent and one for age (composite figure) - For age <20 - 100 - >100, NA
- [ ] keep Dominant vegetation, add unclassified,  + add a other category with 2TD, 2TN or categories with < 500 records in ForC

**Comment by teixeirak** [comment]
@ValentineHerr , overall this looks great!

<img width="756" alt="image" src="https://user-images.githubusercontent.com/6355854/163446176-e2253fe8-3e87-4992-b78f-302d9962ff07.png">

Copied here for reference. Here are a few things I'd tweak:

- [ ] add legend
- [ ] for dominant vegetation, it would be great if we could fit the vegetation type names rather than the codes. 
- [ ] for dominant vegetation, would be best to order with other and then unclassified last
- [ ] for FAO ecozone, again it would be best to put other second-to-last
- [ ] for continent, let's just list them all, and then perhaps we need an "Oceanic" category for other.
- [x] stand age is perfect! :-)

**Comment by ValentineHerr** [comment]
new versions:
![image](https://user-images.githubusercontent.com/19673377/163591480-f2b67a1a-0ab5-4759-b6df-82099caca102.png)

**Comment by teixeirak** [comment]
Looks fantastic! 

In panel A, could you please put "Broadleaf (mixed E/D)" to clarify why these are separate?
And in panel C, could you please change Oceania to "Islands"? (Sorry, I realized that [Oceania](https://en.wikipedia.org/wiki/Oceania) actually refers to a particular geographic region.)

**Comment by teixeirak** [comment]
Also, could you please save .csvs with these numbers so that @mawilliams99 can use them to fill in the results section?

**Comment by ValentineHerr** [comment]
Oceania is actually what is ForC. So I think we can leave it as is. don't you think?

**Comment by teixeirak** [comment]
Yes, it's okay. I verified in the sites table that all with that label are actually Oceania, whereas other islands are associated to continents (e.g., Puerto Rico is North America).

**Comment by teixeirak** [comment]
Perfect; thank you!
