### ISSUE TITLE
why aren't NPP_litter records showing up in variables table?

### ISSUE THREAD

**Issue by teixeirak** [forc-db/IPCC-EFDB-integration#44]
@ValentineHerr , NPP_litter is (and was) in the variables table, and we have 94 records for it in ForC, but it is showing up as 0 records.

**Comment by ValentineHerr** [comment]
Hmmm... good point
I think this is also relevant to #43

**Comment by ValentineHerr** [comment]
This is the list of variables that potentially have the same issue:

 - [ ] delta.biomass  
 - [ ] delta.biomass_root  
 - [ ] delta.biomass_root_coarse  
 - [ ] delta.biomass_root_fine  
 - [ ] delta.deadwood  
 - [ ] delta.deadwood_down  
 - [ ] delta.deadwood_standing  
 - [ ] delta.litter  
 - [ ] delta.soil  
 - [ ] NPP_litter  
 - [ ] R_het_deadwood  
 - [ ] R_het_soil  
 - [ ] woody.mortality  
 - [ ] woody.mortality_root

**Comment by teixeirak** [comment]
Yikes! Let me review this.

**Comment by teixeirak** [comment]
Wait, the only one on the list above that's not flagged to send to IPCC is NPP_litter. The others just have 0 records.

**Comment by teixeirak** [comment]
@ValentineHerr , I think everything here and in #43 should be solved once you re-run.

**Comment by teixeirak** [comment]
Fixed. Thanks!
