### ISSUE TITLE
update histogram figure

### ISSUE THREAD

**Issue by teixeirak** [forc-db/IPCC-EFDB-integration#63]
@ValentineHerr , regarding changes to the histogram figure (pasted below for reference), I think it would be good to follow reviewer 1's suggestion of incorporating estimates of the area in each category. We could either:
(1) add a second y-axis and have paired (thinner) bars showing the relative area in each category, or 
(2) divide by area in each category to get record density.

Option 1 provides more information and does not raise a problem with stand age (for which maps exist but are not reliable).
Option 2 is more concise, but loses the raw numbers of records, which I do think is valuable. 
So, if option 1 seems doable to you, let's go with that.

![image](https://github.com/forc-db/IPCC-EFDB-integration/assets/6355854/3f6ba26d-777f-4c33-a180-6645af1e97c6)

**Comment by ValentineHerr** [comment]
@teixeirak, do we have a map of stand age? I don't recall where that would be if we do.

**Comment by teixeirak** [comment]
I don't think we've ever used a map of stand age, but there is one available: https://essd.copernicus.org/articles/13/4881/2021/. I wouldn't trust it to be super accurate, but I do see it as sufficient for this purpose.

**Comment by ValentineHerr** [comment]
I am downloading the data.

FYI:

> 
> "I further guarantee that I will inform the Data provider(s) and invite them to contribute to the work with additional intellectual inputs, analysis, discussion that - if provided - would lead to co-authorship. The invitation to contribute will be based on a draft manuscript/presentation with first results open enough to be discussed and changed on the basis of the feedbacks from Data providers.
> 
> Email to owner sbesnard@bgc-jena.mpg.de has been sent.
> 
> Email to owner nuno.carvalhais@bgc-jena.mpg.de has been sent.
> "

**Comment by ValentineHerr** [comment]
@teixeirak the their are 4 estimates of stand age: without tree cover correction and with 10%, 20% or 30% tree cover correction.

do you have a strong idea about wich one to use?
Here is a plot in the paper that compres no correctionvs 30% correction (which usually estimates the age higher)
![image](https://github.com/forc-db/IPCC-EFDB-integration/assets/19673377/88196a3a-8624-4b13-bc95-d223f5417908)

**Comment by teixeirak** [comment]
I don't know offhand/ would need to figure out how the corrections work. Do you understand how they work/ have an opinion as to which would be best?

**Comment by teixeirak** [comment]
I noticed that they used a 10% correction in Fig. 6. Perhaps follow that?

**Comment by teixeirak** [comment]
Looks good, thanks!

**Comment by teixeirak** [comment]
@ValentineHerr , could you please make a couple small cosmetic changes here:
- [ ]  add letters to panels
- [ ] move legend to inside panel (a) or (b)

**Comment by ValentineHerr** [comment]
Note that my last update of histogram must have taken into account the new relevant variable (since doc/ForC-EFDB_mapping/ForC_variables_mapping.csv was updated).

also, I messed up the order in Stand age, will update soon.

**Comment by ValentineHerr** [comment]
> Note that my last update of histogram must have taken into account the new relevant variable selection (since doc/ForC-EFDB_mapping/ForC_variables_mapping.csv was updated), but is not visibly noticeable in the histogram.
> 
> also, I messed up the order in Stand age, will update soon.
