### ISSUE TITLE
clarify how to categorize <20 yr old forests following severe disturbance of forest or unknown land use

### ISSUE THREAD

**Issue by teixeirak** [forc-db/IPCC-EFDB-integration#7]
my message to Valentyna;

Following up on your answer to question 1, my understanding is that if a forest undergoes severe disturbance (e.g., clear-cut logging, severe fire), the regrowth stands would be considered FF. Is that correct? In the case I described (stand age <20 and the former land use is not recorded in ForC), these could have been severe disturbance to forest land, so it seems LF might not be appropriate? Should these just be classified as Forest Land? Of should we set them aside to look up?

**Comment by teixeirak** [comment]
(These cases can be avoided in the first data delivery.)

**Comment by teixeirak** [comment]
from V:

You are right, in case previous land use for young forest (<20 yr.) is not known, this area could be affected by severe disturbances. Then, please classify it as FF. If the info on the disturbances is available to be input into the EFDB form, it is good to include.

**Comment by teixeirak** [comment]
There are no cases of this in the first data delivery, but we'll eventually need to deal with this.

**Comment by teixeirak** [comment]
Recapping from [these instructions](https://github.com/forc-db/IPCC-EFDB-integration/blob/main/doc/ForC-EFDB_mapping/defining_land_subcategory.md):

if distmrs.type= "Burned", "StandClearing", or there's a missing value code, we don't know PAST LAND-USE. (from looking at `distmrs.type`). 

Our default seems to be to just call this forest land.  

This affects some studies in a funny way:

Here (Tepley_2017), all sites are forest land remaining forest land (having burned in severe fires), yet sites <20 are just classified as forest land because our system doesn't know the previous land use.

<img width="1119" alt="image" src="https://user-images.githubusercontent.com/6355854/136270970-a12a9eb1-acb0-4009-8803-d75f99f09d66.png">

This relates to issue #29. 

@ValentineHerr , any ideas on how we might  deal with this? It seems like adding a past land use field to ForC would be useful (not just for this), but I'm not sure where we'd put it...

**Comment by teixeirak** [comment]
This also affects:

-  n_10_Uhl_1984_sand (2nd batch)
- n_25_Uhl_1984_sand (1st batch)
- n_75_Ishihara_2017_anmf (2nd batch)

**Comment by ValentineHerr** [comment]
@teixeirak, I am concerned that the issue is more complicated as I am realizing now that I have not touched the script creating PLOTS in a very long time and it maybe obsolete.... I think it was made to deal with the previous PLOTS version, manually made, so I don't think it is actually filling some of the columns based on HISTORY but based on what is already in PLOTS.....
That is not good.

So for now, I think it is best to manually edit at time of approval.
