### ISSUE TITLE
filling Technologies/ Practices field  (management)

### ISSUE THREAD

**Issue by teixeirak** [forc-db/IPCC-EFDB-integration#8]
to V:

The Technologies/Practices field requests land subcategory, which seems to be the same as the "2006 source/sink categories..."  Is this correct? If so, do you want the information duplicated there?

from V:

Land-use categories and sub-categories may be further stratified on the basis of land-use practices and biophysical characteristics in order to create more homogeneous spatial units as may be used for emissions estimation. I would suggest avoiding duplicates.

I'm still confused. This needs clarification. 

to V:
So, to clarify, we don’t want to repeat the 2006 Source/Sink Categories here, but if there’s additional information useful for sub-categorization, we should include it here. I still don’t understand what should go here. Would it make sense to put FAO ecozone here rather than putting that under Parameters/Conditions?

**Comment by teixeirak** [comment]
from V:
The example for sub-categorization can be managed and unmanaged forest land. If you don't have a subdivision, better to keep the cell blank. The example for sub-categorization can be managed and unmanaged forest land. If you don't have a subdivision, better to keep the cell blank. Please keep FAO ecozone under parameters/conditions, cause the info structure in the EFDB form is unified.

**Comment by teixeirak** [comment]
@ValentineHerr ,we may be able to use the "managed" field in ForC_simplified to distinguish managed/ unmanaged forest land, but I want to check IPCC definitions.

**Comment by teixeirak** [comment]
From V4_01_Ch1_Introduction.pdf:
"Managed land is land where human interventions and practices have been applied to perform production, ecological or social functions. "

V4_03_Ch3_Representation.pdf:

"Countries should describe the methods and definitions used to determine areas of managed and unmanaged lands. Managed land is land where human interventions and practices have been applied to perform production, ecological or social functions. All land definitions and classifications should be specified at the national level, described in a transparent manner, and be applied consistently over time. "

**Comment by teixeirak** [comment]
I feel that the definition of managed land is vague, including by IPCC, in ForC, and in general...

**Comment by ValentineHerr** [comment]
so maybe just using that "managed" field is enough.  the details would be in Abatement/Control technologies...

**Comment by teixeirak** [comment]
I will leave this issue open, as I don't entirely trust the "management" field.

**Comment by ValentineHerr** [comment]
I think "managed" in ForC_simplified might be more trustfull as for example that site "Collelongo" whose plot is called "Managed" has not Management in "History" but does say "managed" in ForC_simplified.

**Comment by teixeirak** [comment]
ForC simplified pulls anything with management records, and anything with "managed" in plot name

**Comment by ValentineHerr** [comment]
Yes, so that is better, right? 
wait, when you said
> I don't entirely trust the "management" field.

 you meant the one in the mapping document ? do you mean we should remove that entirely?

**Comment by teixeirak** [comment]
I meant the "managed" field in ForC_simplified. It's pretty good, but I don't think it's foolproof. But for now we can use it to fill Technologies/Practices with either "managed forest land" or "unmanaged forest land"

**Comment by ValentineHerr** [comment]
ok, I pushed a new version with that using tag "land subcategory/subdivision" under "Technologies/Practices"

**Comment by teixeirak** [comment]
from Valentyna: "An unmanaged forest land has been input as a subdivision for both groups of values for primary and secondary forests. However, secondary forest can not be considered as unmanaged."

We need to work on clarifying definition of management.

**Comment by teixeirak** [comment]
Relevant here: https://cbmjournal.biomedcentral.com/articles/10.1186/s13021-018-0095-3

**Comment by teixeirak** [comment]
question to Valentyna (5/4)

Can you please help clarify how we should clarify managed/ unmanaged  land? Two parts here: (a) You previously told me that secondary forests cannot be unmanaged? That makes sense for the specific forest that you changed in the initial data set that we sent you (previously cleared by humans), but I don’t think it makes sense in the case of, for example, a remote boreal forest recovering from a natural burn. Wouldn’t the latter be classified as unmanaged? (b) I’ve started to learn more about land classification under UNFCCC (e.g., https://cbmjournal.biomedcentral.com/articles/10.1186/s13021-018-0095-3), and am realizing that the classification is (i) defined differently across countries and (ii) probably not defined the same way as I would define it (or as it might be defined in publications included in ForC). Could you please provide a recommendation here? Should we just skip this field?

**Comment by teixeirak** [comment]
from Valentyna:

 (a) You are right. In case of remote boreal forest recovering from a natural burnt, this can be unmanaged, but the information on this type of natural disturbances together with the info clarifies that "remote"  forest does not have anthropogenic influence should complement the value considered. (b) Yes, usually countries define managed and unmanaged land by themself. If it is not clear from the data source that a land is unmanaged, I would propose not to focus on this subdivision, but to provide all auxiliary info available for each EF.

My response:

Regarding management classes, I think we will just drop the idea of trying to assign this. Accurately assigning management categories would require a better knowledge of how nations are defining these categories, along with greater informational needs from the original publications.

**Comment by teixeirak** [comment]
@ValentineHerr , let's drop this mapping from the script.

**Comment by teixeirak** [comment]
@ValentineHerr , is this done? (When done, you can close this.)

**Comment by ValentineHerr** [comment]
getting my head back into this.

I am correct that dropping this mapping comes to deleting this row in the ForC-EFDB_mapping.csv document ?

![image](https://user-images.githubusercontent.com/19673377/122999372-33005f80-d37c-11eb-9fc6-b0b92ebc199e.png)

**Comment by teixeirak** [comment]
I'm not sure.... I think so. But please just delete the ForC table/field so that we have record of the Technologies/Practices field there.

**Comment by ValentineHerr** [comment]
ok, thanks!
